### PR TITLE
Setup testing SaaS solution integration - codecov

### PR DESCRIPTION
**Pull request by neriyarden**

### CODE REVIEW

**Comment by neriyarden** [comment]
[[Test Solution] Setup testing SaaS solution integration - codecov/coveralls/sonar cloud](https://trello.com/c/m1aja9E2/9-test-solution-setup-testing-saas-solution-integration-codecov-coveralls-sonar-cloud)

**Comment by unicop** [comment]
@neriyarden I approved your request for permissions codecov required

**Comment by neriyarden** [comment]
@unicop the setup is ready. i think it will appear in the codecov app after we merge this PR

**Review by unicop — APPROVED** [review]
Great work and the flags option is cool and very relevant, good choice

**Pull request merged**
